[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"


[dependencies]
aoc = { path = "../aoc" }
itertools = "0.14.0"
memoize = "0.5.1"
nom = "8.0.0"
pathfinding = "4.14.0"
rayon = "1.11.0"
strum = "0.26.3"
